# Generated by Django 4.2.7 on 2024-01-14 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('total_rate', models.PositiveIntegerField()),
                ('education', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='training/images')),
                ('resume', models.FileField(blank=True, null=True, upload_to='training/resumes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('total_rate', models.PositiveIntegerField()),
                ('class_fee', models.FloatField()),
                ('remined_capacity', models.PositiveIntegerField()),
                ('class_time', models.TimeField()),
                ('days_of_week', multiselectfield.db.fields.MultiSelectField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traing_classes', models.ManyToManyField(to='training.trainingcourse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
